using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WBSSLStore.Domain
{
    public enum EmailType
    {
        CUSTOMER_WELCOME_EMAIL = 0,
        CUSTOMER_CHANGE_PASSWORD = 1,
        CUSTOMER_NEW_ORDER = 2,
        CUSTOMER_REFUND_NOTIFICATION = 3,
        CUSTOMER_SUPPORT_NOTIFICATION = 4,
        CUSTOMER_RENEWAL_30 = 5,
        CUSTOMER_RENEWAL_15 = 6,
        CUSTOMER_RENEWAL_7 = 7,
        CUSTOMER_RENEWAL_3 = 8,
        RESELLER_WELCOME_EMAIL = 9,
        RESELLER_ACCOUNT_ACTIVATION_EMAIL = 10,
        RESELLER_CHANGE_PASSWORD_EMAIL = 11,
        RESELLER_NEW_ORDER_EMAIL = 12,
        RESELLER_ORDER_CANCELLATION = 13,
        RESELLER_REFUND_NOTIFICATION = 14,
        RESELLER_SUPPORT_NOTIFICATION = 15,
        RESELLER_SLAB_CHANGED_NOTIFICATION = 16,
        RESELLER_RENEWAL_30 = 17,
        RESELLER_RENEWAL_15 = 18,
        RESELLER_RENEWAL_7 = 19,
        RESELLER_RENEWAL_3 = 20,
        RESELLER_CUSTOMER_RENEWAL_30 = 21,
        RESELLER_CUSTOMER_RENEWAL_15 = 22,
        RESELLER_CUSTOMER_RENEWAL_7 = 23,
        RESELLER_CUSTOMER_RENEWAL_3 = 24,
        ADMIN_NEW_CUSTOMER = 25,
        ADMIN_NEW_RESELLER = 26,
        ADMIN_CHANGE_PASSWORD = 27,
        ADMIN_NEW_ORDER = 28,
        ADMIN_ORDER_CANCELLATION = 29,
        ADMIN_REFUND_NOTIFICATION = 30,
        ADMIN_SUPPORT_NOTIFICATION = 31,
        ADMIN_ADD_FUND_NOTIFICATION = 32,
        SUPPORT_FRAUDORDER_NOTIFICATION = 33,
        ALL_FORGOTPASSWORD = 34,
        ADMIN_NEWUSER_WELCOME_EMAIL = 35,
        CONTACTUS_EMAIL = 36,
        NeedAdvice_EMAIL = 37,
        RequestForQuote_EMAIL = 38 
    }
}
