//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBSSLStore.Resources.LongText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WBSSLStore.Resources.LongText.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account &amp; Password.
        /// </summary>
        public static string Account_password {
            get {
                return ResourceManager.GetString("Account_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account to checkout faster.
        /// </summary>
        public static string Account_to_checkout_faster {
            get {
                return ResourceManager.GetString("Account_to_checkout_faster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All prices are in.
        /// </summary>
        public static string All_prices_in {
            get {
                return ResourceManager.GetString("All_prices_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions concerning this invoice, contact us at.
        /// </summary>
        public static string Any_Questions {
            get {
                return ResourceManager.GetString("Any_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change banner image just select any banner image and click on &quot;Insert/edit Image&quot; icon and upload your own new banner(s). Please use 960px X 150px(width X height).
        /// </summary>
        public static string Banner_Note {
            get {
                return ResourceManager.GetString("Banner_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this CSR Decoder to decode your Certificate Signing Request and and verify that it contains the correct information. A Certificate Signing Request is a block of encoded text that contains information about the company that an SSL certificate will be issued to and the SSL public key. Once a CSR is created it is difficult to verify what information is contained in it because it is encoded. Since certificate authorities use the information in CSRs to create the certificate, you need to decode CSRs to make  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CheckCSRNote {
            get {
                return ResourceManager.GetString("CheckCSRNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order details will be sent to this email address..
        /// </summary>
        public static string Checkout_Desc {
            get {
                return ResourceManager.GetString("Checkout_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review and submit your order by selecting &quot;Confirm&quot;..
        /// </summary>
        public static string CheckOut_Note {
            get {
                return ResourceManager.GetString("CheckOut_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SSL Checker will help you diagnose problems with your SSL certificate installation.
        ///    You can verify the SSL certificate on your web server to make sure it is correctly
        ///    installed, valid, trusted and doesn&apos;t give any errors to any of your users. To use
        ///    the SSL Checker, simply enter your server&apos;s hostname (must be public) in the boxbelow and click the Submit button.
        /// </summary>
        public static string CheckSSLNote {
            get {
                return ResourceManager.GetString("CheckSSLNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Signing, through the use of digital signatures, enables software developers to include information about themselves and their code with their software. Your end users who download digitally signed 32-bit or 64-bit Portable Executable (.exe, .ocx, .dll or other) or .cab files can be confident that code really comes from you and has not been altered or corrupted since it was created and signed..
        /// </summary>
        public static string Comodo_Code_Signing_Certificates_Desc {
            get {
                return ResourceManager.GetString("Comodo_Code_Signing_Certificates_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued within 10 minutes, an Essential SSL Certificate provides a quick cost-effective solution to secure your customer transactions. More importantly, your customers are assured that it is safe to do business with you because sensitive information is encrypted and remains private..
        /// </summary>
        public static string Comodo_Essential_SSL_Desc {
            get {
                return ResourceManager.GetString("Comodo_Essential_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128-bit SSL certificates designed for encrypting web sites that handle low-volume online transactions. Trusted by over 99.3% of current Internet users, Essential SSL is the solution for new web sites or environments where trust has been established and entity verification (for identity assurance) is not needed..
        /// </summary>
        public static string Comodo_Essential_SSL_Wildcard_Desc {
            get {
                return ResourceManager.GetString("Comodo_Essential_SSL_Wildcard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV SSL Certificates provide the highest levels of encryption, security and trust. They immediately reassure web site visitors that it is safe to conduct online transactions by turning the address bar green on next generation browsers such as Internet Explorer 7 +, FireFox 3 + and Opera 9.5 +..
        /// </summary>
        public static string Comodo_EV_SSL_Desc {
            get {
                return ResourceManager.GetString("Comodo_EV_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard sensitive customer information, financial transactions and transmit confidential data with identity assured Extended Validation (EV) SGC SSL Certificates. These certificates provide 128- or 256-bit encryption to over 99% of Web site visitors by offering the strongest encryption and identity assurance available to every site visitor - even the millions using older versions of Windows and IE..
        /// </summary>
        public static string Comodo_EV_SSL_EV_SGC_Desc {
            get {
                return ResourceManager.GetString("Comodo_EV_SSL_EV_SGC_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Domain EV SSL Certificates (EV MDCs) allow you to secure up to 100 different domains or sub-domains with a single SSL certificate. EV technology adds an additional layer of trust to your online business by turning the browser address bar green every time one of your customers enters the secure area of your web site..
        /// </summary>
        public static string Comodo_EV_SSL_Multi_Domain_Desc {
            get {
                return ResourceManager.GetString("Comodo_EV_SSL_Multi_Domain_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstantSSL Certificates enable you and your customers to complete transactions with the assurance that no one else can read or change information as it travels over the Internet. This leads to increased visitor conversion rate, lower web site abandonment and an increase in average purchase price..
        /// </summary>
        public static string Comodo_Instant_SSL_Desc {
            get {
                return ResourceManager.GetString("Comodo_Instant_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstantSSL Premium Certificates are the professional solution for securing ecommerce web sites and provide compelling visual assurance that your web site can be trusted. InstantSSL Premium Certificates enable your customers to complete transactions with the assurance..
        /// </summary>
        public static string Comodo_Instant_SSL_Premium_Desc {
            get {
                return ResourceManager.GetString("Comodo_Instant_SSL_Premium_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An InstantSSL Pro Certificate enables you and your customers to complete transactions with the assurance that no one else can read or change information as it travels over the Internet. This leads to increased visitor conversion rate, lower web site abandonment and an increase in average purchase price..
        /// </summary>
        public static string Comodo_Instant_SSL_Pro_Desc {
            get {
                return ResourceManager.GetString("Comodo_Instant_SSL_Pro_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-domain certificates (MDC) are your solutions for securing anywhere from two to 100 domains on the same server under one SSL certificate. Consolidate your SSL management process and manage the SSL encryption for all of your domains under just one SSL certificate for multiple domains. You can start by implementing a Comodo Multi-Domain SSL Certificate..
        /// </summary>
        public static string Comodo_Multi_Domain_Desc {
            get {
                return ResourceManager.GetString("Comodo_Multi_Domain_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued within 10 minutes, a Positive SSL Certificate provides a quick cost-effective solution to secure your customer transactions. More importantly, your customers are assured that it is safe to do business with you because sensitive information is encrypted and remains private..
        /// </summary>
        public static string Comodo_Positive_SSL_Desc {
            get {
                return ResourceManager.GetString("Comodo_Positive_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128 bit-SSL certificates designed for encrypting web sites that handle low-volume online transactions. Trusted by over 99.3% of current Internet users, Positive SSL is the solution for new web sites or environments where trust has been established and entity verification (for identity assurance) is not needed. Positive SSL Certificates carry a $10,000 warranty..
        /// </summary>
        public static string Comodo_Positive_SSL_Wildcard_Desc {
            get {
                return ResourceManager.GetString("Comodo_Positive_SSL_Wildcard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo&apos;s Premium SSL Wildcards secure unlimited sub-domains on your site such as www.yourdomain.com, secure.yourdomain.com and mail.yourdomain.com. One Premium SSL Wildcard Certificate saves you money and time by simplifying SSL certificate management. Use a single certificate to secure all of your sub-domains..
        /// </summary>
        public static string Comodo_Premium_SSL_Wildcard_Desc {
            get {
                return ResourceManager.GetString("Comodo_Premium_SSL_Wildcard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo SGC SSL Certificates upgrade the encryption capabilities of older browsers from 40-bit encryption into full 128- or 256-bit encryption. This means your website protects and is trusted by the highest number of internet users possible, even the millions using older versions of Windows and Internet Explorer..
        /// </summary>
        public static string Comodo_SGC_Desc {
            get {
                return ResourceManager.GetString("Comodo_SGC_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure unlimited sub-domains on your website with a single Comodo SGC Wildcard SSL Certificate (e.g. www.yourdomain.com, secure.yourdomain.com, signup.yourdomain.com). A Comodo SGC Wildcard SSL Certificate is a cost effective and efficient means of securing all sub-domains without the need to manage multiple certificates..
        /// </summary>
        public static string Comodo_SGC_Wildcard_Desc {
            get {
                return ResourceManager.GetString("Comodo_SGC_Wildcard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed exclusively for Microsoft Exchange and Office Communications infrastructures, Comodo&apos;s Unified Communications Certificates allow a single certificate to provide SSL-secured communications for multiple domains and multiple host names operating on a single IP address..
        /// </summary>
        public static string Comodo_Unified_Communication_UC_Desc {
            get {
                return ResourceManager.GetString("Comodo_Unified_Communication_UC_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure the following items before your site goes Live..
        /// </summary>
        public static string Dashboard_Note {
            get {
                return ResourceManager.GetString("Dashboard_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Products &amp; its pricing..
        /// </summary>
        public static string Dashboard_Notice1 {
            get {
                return ResourceManager.GetString("Dashboard_Notice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your payment settings..
        /// </summary>
        public static string Dashboard_Notice2 {
            get {
                return ResourceManager.GetString("Dashboard_Notice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your SMTP settings to be able to send out emails from the system..
        /// </summary>
        public static string Dashboard_Notice3 {
            get {
                return ResourceManager.GetString("Dashboard_Notice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Test Mode.
        /// </summary>
        public static string Enable_Test_Mode {
            get {
                return ResourceManager.GetString("Enable_Test_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FreeSSL security certificate is a fully functional security certificate with
        ///a term of 30 days, available completely free of charge. This trial SSL certificate allows you to try before you buy. Since FreeSSL uses the same exact technology as  a RapidSSL certificate (a Symantec subsidiary), you can use it to test RapidSSL before live implementation..
        /// </summary>
        public static string Free_SSL_Desc {
            get {
                return ResourceManager.GetString("Free_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoTrust QuickSSL Premium certificates are the most convenient and cost effective solution for any business that needs to conduct secure online transactions. These certificates enable up to 256-bit encryption and instill confidence and trust in your customers and business partners when providing sensitive information over the Web or mobile devices..
        /// </summary>
        public static string GeoTrust_QuickSSL_Premium_Desc {
            get {
                return ResourceManager.GetString("GeoTrust_QuickSSL_Premium_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure 4 Additional Domains with a Single GeoTrust QuickSSL Premium SAN Certificate GeoTrust, one of the world’s most trusted SSL brand, delivers a SAN/Multi-Domain solution with a fast issuing process at very low cost. GeoTrust now offers their popular QuickSSL Premium certificate with SAN enabled..
        /// </summary>
        public static string GeoTrust_QuickSSL_Premium_multiDomain_Desc {
            get {
                return ResourceManager.GetString("GeoTrust_QuickSSL_Premium_multiDomain_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a strong security statement with the green address bar. GeoTrust® True BusinessID with EV (Extended Validation) Multi-Domain is our premium business-class SSL security product, visually confirming the highest level of authentication available among SSL certificates..
        /// </summary>
        public static string GeoTrust_True_Business_ID_With_EV_Multi_Domain_Desc {
            get {
                return ResourceManager.GetString("GeoTrust_True_Business_ID_With_EV_Multi_Domain_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoTrust® True BusinessID® certificates provide end-to-end Internet security coverage and are ideal for high-profile, high-traffic sites that are likely to be targets for phishing. True BusinessID certificate enables up to 256-bit encryption and an identity verification seal in a single bundle..
        /// </summary>
        public static string GeoTrust_True_BusinessID_Desc {
            get {
                return ResourceManager.GetString("GeoTrust_True_BusinessID_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a True BusinessID Multi-Domain certificate, you can add, edit, or delete up to 25 domain names over the lifetime of the certificate. You can add, edit or delete any additional domain names to the subject alt name (SAN) field during the enrollment process..
        /// </summary>
        public static string GeoTrust_True_BusinessID_Multi_Domain_Desc {
            get {
                return ResourceManager.GetString("GeoTrust_True_BusinessID_Multi_Domain_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True BusinessID Wildcard is the easy, affordable solution. True BusinessID Wildcard is an ideal solution if you need to secure multiple Fully Qualified Domains that share the same base domain name, reside on the same physical server and share the same second-level domain name..
        /// </summary>
        public static string GeoTrust_True_BusinessID_Wildcard_Desc {
            get {
                return ResourceManager.GetString("GeoTrust_True_BusinessID_Wildcard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV SSL can help you to protect your site from phishing scams and increase your customer transactions. True BusinessID with EV comes with the highest levels of identity authentication, up to 256-bit encryption, and the GeoTrust True Site® seal..
        /// </summary>
        public static string GeoTrust_True_BusinessID_with_EV_Desc {
            get {
                return ResourceManager.GetString("GeoTrust_True_BusinessID_with_EV_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never let your site get hacked again, protect you and your potential customers.
        ///You can now add some trust and protect your customer&apos;s online interests with a cost-effective  daily anti-malware scan..
        /// </summary>
        public static string GeotrustAntiMalware_Desc {
            get {
                return ResourceManager.GetString("GeotrustAntiMalware_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have a.
        /// </summary>
        public static string I_have_a {
            get {
                return ResourceManager.GetString("I_have_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All prices are in USD. If you have any questions concerning this invoice, contact us a.
        /// </summary>
        public static string Invoice_Note {
            get {
                return ResourceManager.GetString("Invoice_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We thank you for your business..
        /// </summary>
        public static string InvoiceThankMsg {
            get {
                return ResourceManager.GetString("InvoiceThankMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account to view order summary, account statement, pending orders and other stuff.
        /// </summary>
        public static string Login_Desc {
            get {
                return ResourceManager.GetString("Login_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see Order Detail.
        /// </summary>
        public static string OrderDetClickNote {
            get {
                return ResourceManager.GetString("OrderDetClickNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see Reseller Detail..
        /// </summary>
        public static string OrderDetClickNote2 {
            get {
                return ResourceManager.GetString("OrderDetClickNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see Customer Detail..
        /// </summary>
        public static string OrderDetClickNote3 {
            get {
                return ResourceManager.GetString("OrderDetClickNote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Partner program is based on loyalty, just like a Frequent Flyer program. The    more you sell (or buy) the more you save. And it’s all cumulative. We will add all    your purchases up and as soon as you reach the next level you automatically receive  the additional discounts associated with the higher level tier. Never expires and  continues to add on as you keep selling..
        /// </summary>
        public static string Partner_Pricing_Caption_1 {
            get {
                return ResourceManager.GetString("Partner_Pricing_Caption_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What’s even better is, we’ll give you access to the higher tiers immediately! Simply  either show us your receipts for SSL purchases over the past 2 years or make a deposit to your account. Either way, we will grant you the associated level..
        /// </summary>
        public static string Partner_Pricing_Caption_2 {
            get {
                return ResourceManager.GetString("Partner_Pricing_Caption_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Credit cards will not be charged).
        /// </summary>
        public static string PaymentMethodNote {
            get {
                return ResourceManager.GetString("PaymentMethodNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the desired profit margin (in percentage %) that you would like to add on to your existing purchasing cost. This is applied to all of your products and is the amount you will profit per product. Below are YOUR purchasing prices, to view or manage the prices of individual products, go to Manage Products..
        /// </summary>
        public static string Pricing_Note {
            get {
                return ResourceManager.GetString("Pricing_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidSSL is industry standard 128 / 256 bit single root SSL certificate. RapidSSL certificates have browser recognition of around 99% including IE 5.01+, Netscape 4.7+ and Mozilla 1+ browsers and many other browsers..
        /// </summary>
        public static string RapidSSL_Desc {
            get {
                return ResourceManager.GetString("RapidSSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidSSL is industry standard 128 / 256 bit single root SSL certificate. RapidSSL certificates have browser recognition of around 99% including IE 5.01+, Netscape 4.7+ and Mozilla 1+ browsers and many other browsers. .
        /// </summary>
        public static string RapidSSL_Desc1 {
            get {
                return ResourceManager.GetString("RapidSSL_Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidSSL Wildcard Certificates allows you to secure unlimited number of sub domains on the same domain name with a single certificate. RapidSSL Wildcard is low cost and easy to manage..
        /// </summary>
        public static string RapidSSL_Wildcard_Desc {
            get {
                return ResourceManager.GetString("RapidSSL_Wildcard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the information on this page, When you have completed this review,
        ///        please submit your order for processing.
        /// </summary>
        public static string Reseller_Desc {
            get {
                return ResourceManager.GetString("Reseller_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your.
        /// </summary>
        public static string Sign_in_to_your {
            get {
                return ResourceManager.GetString("Sign_in_to_your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We thank you for your business..
        /// </summary>
        public static string Thanks_biz_msg {
            get {
                return ResourceManager.GetString("Thanks_biz_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the advent of online distribution, developing and disseminating functional code is easier than ever. However, such an environment also subjects code and software to potential dangers presented by fraudulent and malicious code. Don’t expose your customers to these threats. With a Thawte® Code Signing Certificate, you can protect your customers and provide them with the safe, trustworthy code they deserve..
        /// </summary>
        public static string Thawte_Code_Signing_Certificate_Desc {
            get {
                return ResourceManager.GetString("Thawte_Code_Signing_Certificate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte® SGC SuperCert provides SGC SSL certificates with full authentication, and capable of 256-bit encryption with lowest possible encryption level of 128-bit protection for 99.9% of users even with older browsers and browser recognition of around 99%..
        /// </summary>
        public static string Thawte_SGC_SuperCerts_Desc {
            get {
                return ResourceManager.GetString("Thawte_SGC_SuperCerts_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL123 is Thawte&apos;s entry level certificate which provides validation that your domain is registered and that you have authorized the purchase of the certificate..
        /// </summary>
        public static string Thawte_SSL_123_Desc {
            get {
                return ResourceManager.GetString("Thawte_SSL_123_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte® SSL Web Server Certificate is fully authenticated SSL certificates which offers comprehensive authentication procedures with 256, 128, 56 or 40-bit encryption and browser recognition of around 99%..
        /// </summary>
        public static string Thawte_SSL_Web_Server_Desc {
            get {
                return ResourceManager.GetString("Thawte_SSL_Web_Server_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte&apos;s SSL Web Server Certificate with Extended Validation (EV) offers corporations and government entities the highest industry standard for identity authentication as well as 256-, 128-, 56-, or 40-bit encryption..
        /// </summary>
        public static string Thawte_SSL_Web_Server_EV_Desc {
            get {
                return ResourceManager.GetString("Thawte_SSL_Web_Server_EV_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte SSL Webserver Wildcard is an easy, affordable solution if you need to secure multiple fully qualified domains that share the same base domain name, reside on the same physical server, and share the same second level domain name..
        /// </summary>
        public static string Thawte_SSL_Web_Server_Wildcard_Desc {
            get {
                return ResourceManager.GetString("Thawte_SSL_Web_Server_Wildcard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave PCI Product protect the transfer of sensitive data on Web sites, intranets, and extranets using a minimum of 40-bit and up to 256-bit encryption (the highest that each individual browser will allow). It also includes the Trustwave Secured Seal..
        /// </summary>
        public static string TrustKeeper_PCI_DSS_Desc {
            get {
                return ResourceManager.GetString("TrustKeeper_PCI_DSS_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV SSL Certificates are validated to the highest degree to provide consumer confidence in the identity of the web site operator. If you are taking orders online, you need to get the green bar with EV SSL. Customers will receive the green bar as a striking trust indicator in the web browser, and you will see fewer abandoned shopping carts and more conversions. .
        /// </summary>
        public static string TrustKeeper_Plus_EV_SSL_Desc {
            get {
                return ResourceManager.GetString("TrustKeeper_Plus_EV_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave understands the pressure merchants are under to prove compliance with Payment Card Industry Data Security Standard (PCI DSS). TrustKeeper is a certified remote assessment and compliance solution designed to help merchants meet the security standards of all credit card companies..
        /// </summary>
        public static string TrustKeeper_SSL_Plus_Desc {
            get {
                return ResourceManager.GetString("TrustKeeper_SSL_Plus_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave Domain Validated Certificates are best suited for small and medium capital e-commerce web sites. Domain Validated Certificates offer 99% desktop and server browser compatibility with up to 256 bit SSL encryption and 204- bit CSR encryption..
        /// </summary>
        public static string Trustwave_Domain_Validated_SSL_Desc {
            get {
                return ResourceManager.GetString("Trustwave_Domain_Validated_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you an Enterprise looking for our highest warranty? Trustwave Enterprise SSL Certificates provide everything you will need to protect a single domain and assure your customers that your site is trustworthy and secure with our highest Relying Party Warranty on a standard SSL certificate..
        /// </summary>
        public static string Trustwave_Enterprise_SSL_Desc {
            get {
                return ResourceManager.GetString("Trustwave_Enterprise_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV SSL Certificates are validated to the highest degree to provide consumer confidence in the identity of the web site operator. If you are taking orders online, you need to get the green bar with EV SSL. Customers will receive the green bar as a striking trust indicator in the web browser, and you will see fewer abandoned shopping carts and more conversions..
        /// </summary>
        public static string Trustwave_Premium_EV_SSL_Desc {
            get {
                return ResourceManager.GetString("Trustwave_Premium_EV_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need to secure a single server domain name? Trustwave Premium SSL Certificates provide everything you will need to protect a single domain and assure your customers that your site is trustworthy and secure. Every Trustwave SSL Certificate includes a dynamic security site seal to give your customers confidence in your identity and feel safe in doing business with you. .
        /// </summary>
        public static string Trustwave_Premium_SSL_Desc {
            get {
                return ResourceManager.GetString("Trustwave_Premium_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Do you need to secure multiple server sub-domain names? Trustwave Premium Wildcard SSL Certificates provide a quick and easy way to protect multiple sub-domain names and assure your customers that your site is trustworthy and secure. You can use a Trustwave Wildcard SSL certificate to secure domains such as: www.mycompany.com, mail.mycompany.com, secure.mycompany.com and more! Every Trustwave SSL Certificate includes a dynamic security site seal to give your customers confidence in your identity and feel s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Trustwave_Premium_Wildcard_SSL_Desc {
            get {
                return ResourceManager.GetString("Trustwave_Premium_Wildcard_SSL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave Secure E-Mail Digital IDs allow you and your organization to secure your email communications in a cost-effective manner. With this certificate, you can ensure the privacy of both your email messages and attachments quickly and effortlessly..
        /// </summary>
        public static string Trustwave_Secure_Email_Digital_ID_Desc {
            get {
                return ResourceManager.GetString("Trustwave_Secure_Email_Digital_ID_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Your Moneybookers Email Address!.
        /// </summary>
        public static string UseMoneybookers {
            get {
                return ResourceManager.GetString("UseMoneybookers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Your PayPal Email Address!.
        /// </summary>
        public static string UsePaypal {
            get {
                return ResourceManager.GetString("UsePaypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the information on this page, When you have completed this review,
        ///        please submit your order for processing.
        /// </summary>
        public static string UserProfile_Desc {
            get {
                return ResourceManager.GetString("UserProfile_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For developers and software publishers of active content, code signing reduces error messages and builds trust. VeriSign® Code Signing Certificates for Microsoft® Authenticode® authenticate your identity and validate code integrity.
        /// </summary>
        public static string VeriSign_Code_Signing_Certificate_Desc {
            get {
                return ResourceManager.GetString("VeriSign_Code_Signing_Certificate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A VeriSign Secure Site SSL certificate provides a minimum of 40-bit up to 256-bit encryption and more than 99% browser recognition. It also includes a $100,000 warranty and the VeriSign Secured Seal..
        /// </summary>
        public static string VeriSign_Secure_Site_Desc {
            get {
                return ResourceManager.GetString("VeriSign_Secure_Site_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriSign Secure Site Pro SSL Certificate provides 128-bit encryption. Secure Site Pro is enabled by Server Gated Cryptography (SGC) to help ensure strong encryption site visitors..
        /// </summary>
        public static string VeriSign_Secure_Site_Pro_Desc {
            get {
                return ResourceManager.GetString("VeriSign_Secure_Site_Pro_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A VeriSign Secure Site Pro SSL certificate provides 128-bit encryption. Secure Site Pro is enabled by Server Gated Cryptography (SGC) to help ensure strong encryption for site visitors. It also includes a $250,000 warranty and the VeriSign Secured Seal..
        /// </summary>
        public static string VeriSign_Secure_Site_Pro_SGC_Desc {
            get {
                return ResourceManager.GetString("VeriSign_Secure_Site_Pro_SGC_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A VeriSign Secure Site Pro with EV SSL certificate provides a minimum of 128-bit up to 256-bit encryption and more than 99% browser recognition..
        /// </summary>
        public static string VeriSign_Secure_Site_Pro_with_EV_Desc {
            get {
                return ResourceManager.GetString("VeriSign_Secure_Site_Pro_with_EV_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriSign Secure Site with EV SSL Certificate provides minimum of 40-bit and up to 256-bit encryption and more than 99% browser recognition. It also includes a $100,000 warranty and the VeriSign Secured Seal..
        /// </summary>
        public static string VeriSign_Secure_Site_with_EV_Desc {
            get {
                return ResourceManager.GetString("VeriSign_Secure_Site_with_EV_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust turns visitors into customers, develops repeat business and increases sales. The VeriSign Trust™ Seal helps to bring trust to your web site by authenticating your business, protecting it from malware and increasing its recognition and confidence by displaying the VeriSign brand..
        /// </summary>
        public static string VeriSign_Trust_Seal_Desc {
            get {
                return ResourceManager.GetString("VeriSign_Trust_Seal_Desc", resourceCulture);
            }
        }
    }
}
