//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBSSLStore.Resources.NavigationResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WBSSLStore.Resources.NavigationResource.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo.
        /// </summary>
        public static string comodo {
            get {
                return ResourceManager.GetString("comodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Code Signing Certificates.
        /// </summary>
        public static string comodocodesigningcertificates {
            get {
                return ResourceManager.GetString("comodocodesigningcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Essential SSL Certificates.
        /// </summary>
        public static string comodoessentialsslcertificates {
            get {
                return ResourceManager.GetString("comodoessentialsslcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo EV SSL Certificate.
        /// </summary>
        public static string comodoevsslcertificate {
            get {
                return ResourceManager.GetString("comodoevsslcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo EV SSL Multi Domain Certificates.
        /// </summary>
        public static string comodoevsslmultidomaincertificates {
            get {
                return ResourceManager.GetString("comodoevsslmultidomaincertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo EV SSL SGC.
        /// </summary>
        public static string comodoevsslsgc {
            get {
                return ResourceManager.GetString("comodoevsslsgc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Instant SSL.
        /// </summary>
        public static string comodoinstantssl {
            get {
                return ResourceManager.GetString("comodoinstantssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Instant SSL Premium.
        /// </summary>
        public static string comodoinstantsslpremium {
            get {
                return ResourceManager.GetString("comodoinstantsslpremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Instant SSL Pro.
        /// </summary>
        public static string comodoinstantsslpro {
            get {
                return ResourceManager.GetString("comodoinstantsslpro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Multiple Domain Certificate.
        /// </summary>
        public static string comodomultipledomaincertificate {
            get {
                return ResourceManager.GetString("comodomultipledomaincertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Positive SSL Certificates.
        /// </summary>
        public static string comodopositivesslcertificates {
            get {
                return ResourceManager.GetString("comodopositivesslcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Positive SSL Wildcard.
        /// </summary>
        public static string comodopositivesslwildcard {
            get {
                return ResourceManager.GetString("comodopositivesslwildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Premium Wildcard.
        /// </summary>
        public static string comodopremiumwildcard {
            get {
                return ResourceManager.GetString("comodopremiumwildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo SGC (SGC).
        /// </summary>
        public static string comodosgcsgc {
            get {
                return ResourceManager.GetString("comodosgcsgc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo SGC Wildcard.
        /// </summary>
        public static string comodosgcwildcard {
            get {
                return ResourceManager.GetString("comodosgcwildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo Unified Communication (UC).
        /// </summary>
        public static string comodounifiedcommunicationuc {
            get {
                return ResourceManager.GetString("comodounifiedcommunicationuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geotrust.
        /// </summary>
        public static string geotrust {
            get {
                return ResourceManager.GetString("geotrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoTrust QuickSSL Premium Certificates.
        /// </summary>
        public static string geotrustquicksslpremiumcertificates {
            get {
                return ResourceManager.GetString("geotrustquicksslpremiumcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoTrust True BusinessID certificates.
        /// </summary>
        public static string geotrusttruebusinessidcertificates {
            get {
                return ResourceManager.GetString("geotrusttruebusinessidcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoTrust True BusinessID Multi-Domain Certificates.
        /// </summary>
        public static string geotrusttruebusinessidmultidomaincertificates {
            get {
                return ResourceManager.GetString("geotrusttruebusinessidmultidomaincertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoTrust True BusinessID Wildcard Certificates.
        /// </summary>
        public static string geotrusttruebusinessidwildcardcertificates {
            get {
                return ResourceManager.GetString("geotrusttruebusinessidwildcardcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoTrust True BusinessID with Extended Validation (EV).
        /// </summary>
        public static string geotrusttruebusinessidwithextendedvalidationev {
            get {
                return ResourceManager.GetString("geotrusttruebusinessidwithextendedvalidationev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoTrust True BusinessID with Extended Validation (EV) Multi Domain.
        /// </summary>
        public static string geotrusttruebusinessidwithextendedvalidationevmultidomain {
            get {
                return ResourceManager.GetString("geotrusttruebusinessidwithextendedvalidationevmultidomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string privacypolicy {
            get {
                return ResourceManager.GetString("privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidSSL.
        /// </summary>
        public static string rapidssl {
            get {
                return ResourceManager.GetString("rapidssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidSSL Certificates.
        /// </summary>
        public static string rapidsslcertificates {
            get {
                return ResourceManager.GetString("rapidsslcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidSSL Wildcard Certificates.
        /// </summary>
        public static string rapidsslwildcardcertificates {
            get {
                return ResourceManager.GetString("rapidsslwildcardcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string recommendations {
            get {
                return ResourceManager.GetString("recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Policy.
        /// </summary>
        public static string refundpolicy {
            get {
                return ResourceManager.GetString("refundpolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseller Program.
        /// </summary>
        public static string resellerprogram {
            get {
                return ResourceManager.GetString("resellerprogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Comparison.
        /// </summary>
        public static string sslcomparison {
            get {
                return ResourceManager.GetString("sslcomparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte.
        /// </summary>
        public static string thawte {
            get {
                return ResourceManager.GetString("thawte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte Code Signing Certificate .
        /// </summary>
        public static string thawtecodesigningcertificate {
            get {
                return ResourceManager.GetString("thawtecodesigningcertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte SGC SuperCerts.
        /// </summary>
        public static string thawtesgcsupercerts {
            get {
                return ResourceManager.GetString("thawtesgcsupercerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte SSL 123 Web Server.
        /// </summary>
        public static string thawtessl123webserver {
            get {
                return ResourceManager.GetString("thawtessl123webserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte SSL Web Server Certificates.
        /// </summary>
        public static string thawtesslwebservercertificates {
            get {
                return ResourceManager.GetString("thawtesslwebservercertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte SSL Web Server EV Certificates.
        /// </summary>
        public static string thawtesslwebserverevcertificates {
            get {
                return ResourceManager.GetString("thawtesslwebserverevcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thawte SSL Web Server Wildcard Certificates.
        /// </summary>
        public static string thawtesslwebserverwildcardcertificates {
            get {
                return ResourceManager.GetString("thawtesslwebserverwildcardcertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrustKeeper PCI Compliance.
        /// </summary>
        public static string trustkeeperpcicompliance {
            get {
                return ResourceManager.GetString("trustkeeperpcicompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrustKeeper Plus EV SSL.
        /// </summary>
        public static string trustkeeperplusevssl {
            get {
                return ResourceManager.GetString("trustkeeperplusevssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrustKeeper SSL Plus.
        /// </summary>
        public static string trustkeepersslplus {
            get {
                return ResourceManager.GetString("trustkeepersslplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrustWave.
        /// </summary>
        public static string trustwave {
            get {
                return ResourceManager.GetString("trustwave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave Code Signing.
        /// </summary>
        public static string trustwavecodesigning {
            get {
                return ResourceManager.GetString("trustwavecodesigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave Domain Validated SSL.
        /// </summary>
        public static string trustwavedomainvalidatedssl {
            get {
                return ResourceManager.GetString("trustwavedomainvalidatedssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave Enterprise SSL.
        /// </summary>
        public static string trustwaveenterprisessl {
            get {
                return ResourceManager.GetString("trustwaveenterprisessl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave Premium EV SSL.
        /// </summary>
        public static string trustwavepremiumevssl {
            get {
                return ResourceManager.GetString("trustwavepremiumevssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave Premium SSL.
        /// </summary>
        public static string trustwavepremiumssl {
            get {
                return ResourceManager.GetString("trustwavepremiumssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave Premium Wildcard SSL.
        /// </summary>
        public static string trustwavepremiumwildcardssl {
            get {
                return ResourceManager.GetString("trustwavepremiumwildcardssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustwave Secure Email Digital ID.
        /// </summary>
        public static string trustwavesecureemaildigitalid {
            get {
                return ResourceManager.GetString("trustwavesecureemaildigitalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriSign.
        /// </summary>
        public static string verisign {
            get {
                return ResourceManager.GetString("verisign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriSign Code Signing.
        /// </summary>
        public static string verisigncodesigning {
            get {
                return ResourceManager.GetString("verisigncodesigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriSign Secure Site.
        /// </summary>
        public static string verisignsecuresite {
            get {
                return ResourceManager.GetString("verisignsecuresite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriSign Secure Site Pro.
        /// </summary>
        public static string verisignsecuresitepro {
            get {
                return ResourceManager.GetString("verisignsecuresitepro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriSign Secure Site Pro with EV.
        /// </summary>
        public static string verisignsecuresiteprowithev {
            get {
                return ResourceManager.GetString("verisignsecuresiteprowithev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriSign Secure Site with EV.
        /// </summary>
        public static string verisignsecuresitewithev {
            get {
                return ResourceManager.GetString("verisignsecuresitewithev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriSign Trust Seal.
        /// </summary>
        public static string verisigntrustseal {
            get {
                return ResourceManager.GetString("verisigntrustseal", resourceCulture);
            }
        }
    }
}
