//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBSSLStore.Resources.ErrorMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WBSSLStore.Resources.ErrorMessage.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Admin Email.
        /// </summary>
        public static string AdminEmailRequired {
            get {
                return ResourceManager.GetString("AdminEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter alias..
        /// </summary>
        public static string AliasRequired {
            get {
                return ResourceManager.GetString("AliasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Amount.
        /// </summary>
        public static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should be greater than Zero (0)..
        /// </summary>
        public static string AmtGreaterthanzero {
            get {
                return ResourceManager.GetString("AmtGreaterthanzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter api partner code..
        /// </summary>
        public static string APIPartnerCodeRequired {
            get {
                return ResourceManager.GetString("APIPartnerCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter api password..
        /// </summary>
        public static string APIPasswordRequired {
            get {
                return ResourceManager.GetString("APIPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter api user name..
        /// </summary>
        public static string APIUsernameRequired {
            get {
                return ResourceManager.GetString("APIUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter approver email..
        /// </summary>
        public static string ApproverEmailRequired {
            get {
                return ResourceManager.GetString("ApproverEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this promocode?.
        /// </summary>
        public static string AskToDeletePromocode {
            get {
                return ResourceManager.GetString("AskToDeletePromocode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during autentication process. Please try again..
        /// </summary>
        public static string Autherr {
            get {
                return ResourceManager.GetString("Autherr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Billing Email.
        /// </summary>
        public static string BillingEmailRequired {
            get {
                return ResourceManager.GetString("BillingEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Blog URL.
        /// </summary>
        public static string BlogUrlRequired {
            get {
                return ResourceManager.GetString("BlogUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select brand..
        /// </summary>
        public static string BrandNameRequired {
            get {
                return ResourceManager.GetString("BrandNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand updated successfully, Please Save Settings..
        /// </summary>
        public static string BrandSettingUpdate {
            get {
                return ResourceManager.GetString("BrandSettingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter campaign name..
        /// </summary>
        public static string CampaignNameRequired {
            get {
                return ResourceManager.GetString("CampaignNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter comment..
        /// </summary>
        public static string CancelCommentRequired {
            get {
                return ResourceManager.GetString("CancelCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Reason..
        /// </summary>
        public static string CancelReasonRequired {
            get {
                return ResourceManager.GetString("CancelReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Card Type..
        /// </summary>
        public static string CardTypeRequired {
            get {
                return ResourceManager.GetString("CardTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name on card..
        /// </summary>
        public static string CCNameRequired {
            get {
                return ResourceManager.GetString("CCNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter city..
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter comments..
        /// </summary>
        public static string CommentsRequired {
            get {
                return ResourceManager.GetString("CommentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter common name.
        /// </summary>
        public static string CommonNameRequired {
            get {
                return ResourceManager.GetString("CommonNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter company name..
        /// </summary>
        public static string CompanyNameRequired {
            get {
                return ResourceManager.GetString("CompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password and password do not match..
        /// </summary>
        public static string ComparPassword {
            get {
                return ResourceManager.GetString("ComparPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update contract status..
        /// </summary>
        public static string ContactNotSuccess {
            get {
                return ResourceManager.GetString("ContactNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this contract?.
        /// </summary>
        public static string ContractAreYouSure {
            get {
                return ResourceManager.GetString("ContractAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract deleted successfully..
        /// </summary>
        public static string Contractdeleted {
            get {
                return ResourceManager.GetString("Contractdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select contract name..
        /// </summary>
        public static string ContractIDRequired {
            get {
                return ResourceManager.GetString("ContractIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value between 1 to 99999999.
        /// </summary>
        public static string ContractLevelRequired {
            get {
                return ResourceManager.GetString("ContractLevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter contract name..
        /// </summary>
        public static string ContractNameRequired {
            get {
                return ResourceManager.GetString("ContractNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete contract..
        /// </summary>
        public static string ContractNotdeleted {
            get {
                return ResourceManager.GetString("ContractNotdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract status updated successfully..
        /// </summary>
        public static string ContractSuccess {
            get {
                return ResourceManager.GetString("ContractSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter country name..
        /// </summary>
        public static string CountryNameRequired {
            get {
                return ResourceManager.GetString("CountryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter csr..
        /// </summary>
        public static string CSRRequired {
            get {
                return ResourceManager.GetString("CSRRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not resolve to an IP address. Please make sure your DNS records are set up correctly..
        /// </summary>
        public static string CSRToolErrmsg {
            get {
                return ResourceManager.GetString("CSRToolErrmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plese select currency..
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter CVV min 3 or max 4..
        /// </summary>
        public static string CVVnumber {
            get {
                return ResourceManager.GetString("CVVnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date created..
        /// </summary>
        public static string DateCreatedRequired {
            get {
                return ResourceManager.GetString("DateCreatedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter discount..
        /// </summary>
        public static string DiscountRequired {
            get {
                return ResourceManager.GetString("DiscountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter domain name..
        /// </summary>
        public static string DomainNameRequired {
            get {
                return ResourceManager.GetString("DomainNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exist.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email from..
        /// </summary>
        public static string EmailFromRequired {
            get {
                return ResourceManager.GetString("EmailFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email to..
        /// </summary>
        public static string EmailTORequired {
            get {
                return ResourceManager.GetString("EmailTORequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Facebook URL.
        /// </summary>
        public static string FbValidUrl {
            get {
                return ResourceManager.GetString("FbValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Fromdate.
        /// </summary>
        public static string Fromdate {
            get {
                return ResourceManager.GetString("Fromdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gateway name.
        /// </summary>
        public static string gatewayNameRequired {
            get {
                return ResourceManager.GetString("gatewayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image url.
        /// </summary>
        public static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change visibility.
        /// </summary>
        public static string InVisibility {
            get {
                return ResourceManager.GetString("InVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter invoice prefix..
        /// </summary>
        public static string InvoicePrifxRequired {
            get {
                return ResourceManager.GetString("InvoicePrifxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter keyfilepath.
        /// </summary>
        public static string keyfilepathRequired {
            get {
                return ResourceManager.GetString("keyfilepathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter kaywords..
        /// </summary>
        public static string KeywordsRequired {
            get {
                return ResourceManager.GetString("KeywordsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter language code..
        /// </summary>
        public static string LangCodeRequired {
            get {
                return ResourceManager.GetString("LangCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter language name..
        /// </summary>
        public static string LangNameRequired {
            get {
                return ResourceManager.GetString("LangNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter last name..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter liveurl.
        /// </summary>
        public static string LiveUrlRequired {
            get {
                return ResourceManager.GetString("LiveUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter LoginID.
        /// </summary>
        public static string LoginIdRequired {
            get {
                return ResourceManager.GetString("LoginIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter MerchantID.
        /// </summary>
        public static string MerIDRequired {
            get {
                return ResourceManager.GetString("MerIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter moneybookersid.
        /// </summary>
        public static string MoneybookersIDRequired {
            get {
                return ResourceManager.GetString("MoneybookersIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment gateway selected..
        /// </summary>
        public static string NoGatewaySelected {
            get {
                return ResourceManager.GetString("NoGatewaySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least one year price.
        /// </summary>
        public static string NoPricingAdded {
            get {
                return ResourceManager.GetString("NoPricingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number of months..
        /// </summary>
        public static string NumberOfMonthsRequired {
            get {
                return ResourceManager.GetString("NumberOfMonthsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter page name..
        /// </summary>
        public static string PageNameRequired {
            get {
                return ResourceManager.GetString("PageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Page Size.
        /// </summary>
        public static string PageSizeRequired {
            get {
                return ResourceManager.GetString("PageSizeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter PartnerID.
        /// </summary>
        public static string PartnerIDRequired {
            get {
                return ResourceManager.GetString("PartnerIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter payment gateway name..
        /// </summary>
        public static string PaymentGatewayNameRequired {
            get {
                return ResourceManager.GetString("PaymentGatewayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select payment method..
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PayPalID must be in the format of name@domain.com..
        /// </summary>
        public static string PaypalID {
            get {
                return ResourceManager.GetString("PaypalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter paypalid.
        /// </summary>
        public static string PaypalIdRequired {
            get {
                return ResourceManager.GetString("PaypalIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone..
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during process. Please contact administrator..
        /// </summary>
        public static string ProcessError {
            get {
                return ResourceManager.GetString("ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this product?.
        /// </summary>
        public static string ProductAskDelete {
            get {
                return ResourceManager.GetString("ProductAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter product code..
        /// </summary>
        public static string ProductCodeRequired {
            get {
                return ResourceManager.GetString("ProductCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deleted successfully..
        /// </summary>
        public static string ProductDeleteSuccess {
            get {
                return ResourceManager.GetString("ProductDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete product..
        /// </summary>
        public static string ProductDeleteUnSuccess {
            get {
                return ResourceManager.GetString("ProductDeleteUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter product description..
        /// </summary>
        public static string ProductDescriptionRequired {
            get {
                return ResourceManager.GetString("ProductDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select product..
        /// </summary>
        public static string ProductIDRequired {
            get {
                return ResourceManager.GetString("ProductIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter product name..
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product status updated successfully..
        /// </summary>
        public static string ProductUpdateSuccess {
            get {
                return ResourceManager.GetString("ProductUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update product status..
        /// </summary>
        public static string ProductUpdateUnSuccess {
            get {
                return ResourceManager.GetString("ProductUpdateUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid profit margin..
        /// </summary>
        public static string ProfitMarginRequired {
            get {
                return ResourceManager.GetString("ProfitMarginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code applied successfully..
        /// </summary>
        public static string PromoAppliedSuccess {
            get {
                return ResourceManager.GetString("PromoAppliedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promocode already exists..
        /// </summary>
        public static string PromocodeAlreadyExist {
            get {
                return ResourceManager.GetString("PromocodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter promo code..
        /// </summary>
        public static string PromoCodeRequired {
            get {
                return ResourceManager.GetString("PromoCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promocode deleted successfully..
        /// </summary>
        public static string PromoDelSuccess {
            get {
                return ResourceManager.GetString("PromoDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Promocode..
        /// </summary>
        public static string PromoDelUnSuccess {
            get {
                return ResourceManager.GetString("PromoDelUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Receipt Details.
        /// </summary>
        public static string ReceiptDetRequired {
            get {
                return ResourceManager.GetString("ReceiptDetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter retail price..
        /// </summary>
        public static string RetailPriceRequired {
            get {
                return ResourceManager.GetString("RetailPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter sales price..
        /// </summary>
        public static string SalesPriceRequired {
            get {
                return ResourceManager.GetString("SalesPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select month..
        /// </summary>
        public static string SelectMonth {
            get {
                return ResourceManager.GetString("SelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select year..
        /// </summary>
        public static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Page URL.
        /// </summary>
        public static string SlugRequired {
            get {
                return ResourceManager.GetString("SlugRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter smtp host..
        /// </summary>
        public static string SMTPHostRequired {
            get {
                return ResourceManager.GetString("SMTPHostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter smtp port.
        /// </summary>
        public static string SMTPPortRequired {
            get {
                return ResourceManager.GetString("SMTPPortRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter staff note..
        /// </summary>
        public static string StaffNoteRequired {
            get {
                return ResourceManager.GetString("StaffNoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter state..
        /// </summary>
        public static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter street..
        /// </summary>
        public static string StreetRequired {
            get {
                return ResourceManager.GetString("StreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter subject..
        /// </summary>
        public static string SubjectRequired {
            get {
                return ResourceManager.GetString("SubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Support Email.
        /// </summary>
        public static string SupportEmailRequired {
            get {
                return ResourceManager.GetString("SupportEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Testimonial Description.
        /// </summary>
        public static string TestimonialDescription {
            get {
                return ResourceManager.GetString("TestimonialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Signature.
        /// </summary>
        public static string TestimonialName {
            get {
                return ResourceManager.GetString("TestimonialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Short Description.
        /// </summary>
        public static string TestimonialShortDescription {
            get {
                return ResourceManager.GetString("TestimonialShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter testurl.
        /// </summary>
        public static string TestUrlRequired {
            get {
                return ResourceManager.GetString("TestUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select timezone..
        /// </summary>
        public static string TimeZoneRequired {
            get {
                return ResourceManager.GetString("TimeZoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter title..
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Todate.
        /// </summary>
        public static string Todate {
            get {
                return ResourceManager.GetString("Todate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter TransactionKey.
        /// </summary>
        public static string TranKeyRequired {
            get {
                return ResourceManager.GetString("TranKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Twitter URL.
        /// </summary>
        public static string TwitterValidURL {
            get {
                return ResourceManager.GetString("TwitterValidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect. Please try again..
        /// </summary>
        public static string UnmandPassWrong {
            get {
                return ResourceManager.GetString("UnmandPassWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist system. Please enter another email address..
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid amount..
        /// </summary>
        public static string ValidAmount {
            get {
                return ResourceManager.GetString("ValidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid page name..
        /// </summary>
        public static string ValidCaption {
            get {
                return ResourceManager.GetString("ValidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number with at least 14 and max 16 characters!..
        /// </summary>
        public static string ValidCCNumber {
            get {
                return ResourceManager.GetString("ValidCCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contract Level must be a number..
        /// </summary>
        public static string ValidContractLevel {
            get {
                return ResourceManager.GetString("ValidContractLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email..
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid moneybookersid.
        /// </summary>
        public static string ValidMoneybookersID {
            get {
                return ResourceManager.GetString("ValidMoneybookersID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain alpha-numeric value with minimum 8 character..
        /// </summary>
        public static string ValidPassword_Caption {
            get {
                return ResourceManager.GetString("ValidPassword_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid paypalid..
        /// </summary>
        public static string ValidPaypalID {
            get {
                return ResourceManager.GetString("ValidPaypalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Promocode.
        /// </summary>
        public static string ValidPromocode {
            get {
                return ResourceManager.GetString("ValidPromocode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Valid Url.
        /// </summary>
        public static string ValidUrl {
            get {
                return ResourceManager.GetString("ValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid user name or password..
        /// </summary>
        public static string ValidUsernameandPass {
            get {
                return ResourceManager.GetString("ValidUsernameandPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid V.A.T. Rate.
        /// </summary>
        public static string ValidVatNo {
            get {
                return ResourceManager.GetString("ValidVatNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select vat country..
        /// </summary>
        public static string VatCountryRequired {
            get {
                return ResourceManager.GetString("VatCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter vat number..
        /// </summary>
        public static string VatNoRequired {
            get {
                return ResourceManager.GetString("VatNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Vat Percent for Selected Country.
        /// </summary>
        public static string VatPerRequired {
            get {
                return ResourceManager.GetString("VatPerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility change successfully..
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter webserver name..
        /// </summary>
        public static string WebServerNameRequired {
            get {
                return ResourceManager.GetString("WebServerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter zip..
        /// </summary>
        public static string ZipRequired {
            get {
                return ResourceManager.GetString("ZipRequired", resourceCulture);
            }
        }
    }
}
